spring.application.name=RecruiteRoom_Backend

# Logging Configuration
logging.level.org.springframework=WARN
logging.level.com=DEBUG

# Server Configuration
server.port=8088

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://Recruit_Room:m7npf89AtmrqhHOn@cluster0.cmksk.mongodb.net/recruitRooms?retryWrites=true&w=majority

# Profile Activation (Ensure application-dev.properties exists, or comment this out)
# spring.profiles.active=dev

# Debug Mode (Set to false for cleaner logs)
debug=false
